version: '3.8'
services:
  node:
    build: 
      dockerfile: dsp-archiwebf22-hm-hm-at-workflow/containers/ci-cd/Dockerfile
      context: ../
    # working_dir: /workflow/current
    container_name: app
    ports:
      - 80:80 
      - 443:443
    restart: always